name: Build site and deploy to GH-Pages on push to main branch
run-name: Build and deploy - Commit = ${{ github.sha }}
on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - closed
    paths:
      - "public/**/*"
      - "src/**/*"
      - ".pnp.cjs"
      - ".pnp.loader.mjs"
      - ".yarnrc.yml"
      - ".yarn/**/*"
      - "yarn.lock"
permissions:
  contents: write

jobs:
  if_merged:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to runner
        id: checkout-main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Checkout to gh-pages branch
        id: checkout-gh-pages
        run: git checkout -B gh-pages

      - name: Build from source
        id: build-from-source
        run: |
          yarn install --immutable
          yarn build

      - name: Deploy webpage
        id: deploy-webpage
        run: |
          mv -f ./build/* ./
          rm -rf ./build
          git config user.email "47836741+mrlucciola@users.noreply.github.com"
          git config user.name "mrlucciola"
          git checkout origin/config -- .nojekyll CNAME
          git add .
          git commit -m 'redeploying'
          git push origin gh-pages --force
